# Generated by Django 3.0.5 on 2020-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'technician'), ('contractor_customer', 'contractor customer'), ('contractor', 'contractor'), ('kovco_staff', 'kovco staff')], default='kovco_staff', max_length=20),
            preserve_default=False,
        ),
    ]
