# Generated by Django 3.0.5 on 2020-04-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'Manage staff.'), ('is_technician', 'Is a technician responsible for device maintainance.'), ('is_contractor', 'Is a contructor who is a direct customer of KovcoLab.'), ('is_contractor_customer', 'Is a customer of KovcoLab contructor who actually owns the device.'))},
        ),
    ]
