# Generated by Django 3.0.5 on 2020-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200405_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_device_imei',
            field=models.CharField(default='', max_length=50, verbose_name='IMEI'),
        ),
    ]
