# Generated by Django 3.0.5 on 2020-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_home_device_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_device_imei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Home device imei'),
        ),
    ]
