# Generated by Django 3.0.5 on 2020-04-25 21:39

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0008_auto_20200405_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_staff', 'Manage staff.'), ('is_technician', 'Is a technician responsible for device maintainance.'), ('is_contractor', 'Is a contructor who is a direct customer of KovcoLab.'), ('is_contractor_customer', 'Is a customer of KovcoLab contructor who actually owns the device.'))},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='user-avatars'),
        ),
    ]
