# Generated by Django 3.0.5 on 2020-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('pk',), 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
