# Generated by Django 3.0.5 on 2020-04-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='device_time_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='contract end date'),
        ),
    ]
