# Generated by Django 3.0.5 on 2020-05-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('unit_name',), 'permissions': (('manage_devices', 'Manage devices.'), ('assign_devices', 'Assign devices to other users.'))},
        ),
    ]
