# Generated by Django 3.0.5 on 2020-04-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200404_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('unit_name',), 'permissions': (('manage_devices', 'Manage devices.'),)},
        ),
    ]
