# Generated by Django 3.0.5 on 2020-05-07 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0003_auto_20200404_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_location', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
