# Generated by Django 3.0.5 on 2020-04-26 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0004_auto_20200425_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
